name: Build and Deploy test

on:
  push:
    branches: [ "main" ]

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/815516096207/locations/global/workloadIdentityPools/my-pool/providers/my-provider'	
        service_account: reg-test@dev-app-c4b8a.iam.gserviceaccount.com

    - name: test auth
      run: |-
        echo ${{steps.auth.outputs.access_token}}
